name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn package

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/my-java-app:latest
        IMAGE_NAME_LC=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
        docker build -t "$IMAGE_NAME_LC" .
        echo "IMAGE_NAME_LC=$IMAGE_NAME_LC" >> $GITHUB_ENV

    - name: Push Docker image
      run: docker push "$IMAGE_NAME_LC"